# Generated by Django 6.0.5 on 2026-05-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("ASSIGNEE_CHANGED", "Assignee Changed"),
                            ("UPDATED", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("ASSIGNEE_CHANGED", "Assignee Changed"),
                            ("UPDATED", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.CharField(blank=True)),
                ("new_value", models.CharField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="boards.task",
                    ),
                ),
            ],
        ),
    ]
