# Generated by Django 6.0.5 on 2026-05-21 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_remove_board_members_task_taskactivity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="members_boards",
                through="boards.BoardMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
