# Generated by Django 6.0.5 on 2026-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0003_taskactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=20,
            ),
        ),
    ]
