# Generated by Django 6.0.5 on 2026-05-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_board_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "permissions": [("manage_board_members", "Can manage board members")]
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("assign_task", "Can assign task")]},
        ),
        migrations.RemoveField(
            model_name="boardmembership",
            name="role",
        ),
    ]
